version: '3.8'

services:
  freemobnotifier:
    build: .
    container_name: freemobnotifier-app
    ports:
      - "18596:3000"  # External port 18596 maps to internal port 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      # PWA Configuration
      - PWA_ENABLED=true
      - APP_NAME=FreeMobNotifier
      - APP_VERSION=1.0.0
      # Trust reverse proxy for real IP and protocol detection
      - TRUST_PROXY=true
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    networks:
      - freemob-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/settings', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  freemob-network:
    driver: bridge
    external: false
    